hmcts/disposer-idam-user

src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Remove health endpoint configs from application.yaml
Remove health endpoint configs from application.yaml
```
[ ] Yes
[x] No
```
=> Remove health endpoint configs from application.yaml

charts/disposer-idam-user-disposer/Chart.yaml
Bump up chart version
Bump up chart version
```
[ ] Yes
[x] No
```
=> Bump up chart version

Jenkinsfile_CNP
Fix Jenkinsfile_CNP
Fix Jenkinsfile_CNP
```
[ ] Yes
[x] No
```
=> Fix Jenkinsfile_CNP

charts/disposer-idam-user-disposer/Chart.yaml
Rename idam disposer
Rename idam disposer
```
[ ] Yes
[x] No
```
=> Rename idam disposer

Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/LAU-630
Fix nightly pipeline
```
[ ] Yes
[x] No
```
=> Fix nightly pipeline

.github/dependabot.yml
https://tools.hmcts.net/jira/browse/LAU-690
This is to configure dependabot
```
[ ] Yes
[x] No
```
=> LAU-690 dependabot configuration

src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/AbstractSteps.java, src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java
https://tools.hmcts.net/jira/browse/LAU-632
Added size parameter to stale users fetch to specify how many users to fetch
```
[ ] Yes
[x] No
```
=> LAU-632 make configurable stale users fetch batch size

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-710
Added secret method
```
[ ] Yes
[x] No
```
=> LAU-710 missing secret method

src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/RetrySteps.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/SpringBootIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/UserDisposerSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/WireMockStubs.java, src/integrationTest/resources/application-test.yaml, src/integrationTest/resources/features/user_disposer.feature, src/main/java/uk/gov/hmcts/reform/idam/Application.java, src/main/java/uk/gov/hmcts/reform/idam/service/DeleteUserService.java, src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java, src/main/java/uk/gov/hmcts/reform/idam/service/UserRoleService.java, src/main/java/uk/gov/hmcts/reform/idam/service/aop/MethodRetryAspect.java, src/main/java/uk/gov/hmcts/reform/idam/service/aop/Retry.java, src/main/java/uk/gov/hmcts/reform/idam/util/SecurityUtil.java, src/test/java/uk/gov/hmcts/reform/idam/service/StaleUsersServiceTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/aop/MethodRetryAspectTest.java, src/test/java/uk/gov/hmcts/reform/idam/util/SecurityUtilTest.java
https://tools.hmcts.net/jira/browse/LAU-715
Added Retry annotation that retries feign request on 403 response
```
[ ] Yes
[x] No
```
=> LAU-715 added aspect to retry on feign exception

src/main/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolver.java, src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/idam/parameter/DefaultParameterResolverTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-745
Add request limit parameter
```
[ ] Yes
[x] No
```
=> Add request limit parameter

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/idam/UserDeletionFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/idam/helpers/IdamUserDataProvider.java, src/functionalTest/java/uk/gov/hmcts/reform/idam/helpers/RoleAssignmentProvider.java, src/functionalTest/resources/role-assignment.json, src/main/java/uk/gov/hmcts/reform/idam/service/DeleteUserService.java
https://tools.hmcts.net/jira/browse/LAU-695
Added tests to create users and assigned them roles, to test that they are excluded from deletions.
```
[ ] Yes
[x] No
```
=> LAU-695 functional tests with role assignments

charts/disposer-idam-user/Chart.yaml
Bump chart version to replace prod image version
```
[ ] Yes
[x] No
```
=> Bump chart version to 0.0.12

src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java
Add total number of deleted stale users log.
Add total number of deleted stale users log.
```
[ ] Yes
[x] No
```
=> Add total number of deleted stale users log.

src/functionalTest/java/uk/gov/hmcts/reform/idam/helpers/IdamUserDataProvider.java, src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/main/java/uk/gov/hmcts/reform/idam/service/aop/MethodRetryAspect.java, src/main/java/uk/gov/hmcts/reform/idam/util/SecurityUtil.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-754
Generating token before application start
```
[ ] Yes
[x] No
```
=> LAU-754 Token generation before application run

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/SpringBootIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/UserDisposerSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/WireMockStubs.java, src/integrationTest/resources/features/user_disposer.feature, src/main/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolver.java, src/main/java/uk/gov/hmcts/reform/idam/service/DeleteUserService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolverTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/DeleteUserServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-755
Add Simulation mode
```
[ ] Yes
[x] No
```
=> LAU-755 Add Simulation mode

Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-762
This report added.
```
[ ] Yes
[x] No
```
=> LAU-762 added reports

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/functionalTest/resources/application-functional.yaml
https://tools.hmcts.net/jira/browse/LAU-762
Change functional test report generation after functional test execution
```
[ ] Yes
[x] No
```
=> LAU-762 functional test report reaarange

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/LAU-762
Remove generation of functional test report
```
[ ] Yes
[x] No
```
=> LAU-762 remove functional test report

src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-753
Change is to show correct stale users on summary
```
[ ] Yes
[x] No
```
=> LAU-753 Disposer Idam symmary with correct batch users

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-762
Disable functional test on nightly
```
[ ] Yes
[x] No
```
=> LAU-762 disable funstional test on nightly build

catalog-info.yaml
https://tools.hmcts.net/jira/browse/LAU-764
Adding catalog-info.yaml
```
[ ] Yes
[x] No
```
=> LAU-764 adding catalog-info.yaml

charts/disposer-idam-user/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-764
This change is to upgrade chart version
```
[ ] Yes
[x] No
```
=> LAU-764 upgrading chart version

README.md
https://tools.hmcts.net/jira/browse/LAU-788
Initial README file
```
[ ] Yes
[x] No
```
=> LAU-788 update disposer-idam-user README

.github/renovate.json, Dockerfile, build.gradle
Revert changes that renovate made after tagging release version
```
[ ] Yes
[x] No
```
=> revert renovate changes, disable auto-merge

charts/disposer-idam-user/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-799
Bump job chart version
```
[ ] Yes
[x] No
```
=> LAU-799 bump job chart version

.github/renovate.json
https://tools.hmcts.net/jira/browse/LAU-794
Re-enable auto merge minor version updates
```
[ ] Yes
[x] No
```
=> LAU-794 re-enable auto merge PR

src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/UserDisposerSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/WireMockStubs.java, src/integrationTest/resources/features/user_disposer.feature, src/main/java/uk/gov/hmcts/reform/idam/service/DeleteUserService.java, src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/main/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtils.java, src/test/java/uk/gov/hmcts/reform/idam/service/DeleteUserServiceTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java, src/test/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtilsTest.java
https://tools.hmcts.net/jira/browse/LAU-798
Don't fail on other than 200 user deletion response status code, but count failures
```
[ ] Yes
[x] No
```
=> LAU-798 count failed deletions and print in stats

.github/dependabot.yml
https://tools.hmcts.net/jira/browse/LAU-802
Remove dependabot
```
[ ] Yes
[x] No
```
=> LAU-802 remove dependabot

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/UserDisposerSteps.java
https://tools.hmcts.net/jira/browse/LAU-800
Run integration tests on build
```
[ ] Yes
[x] No
```
=> LAU-800 run integration tests on build

build.gradle
https://tools.hmcts.net/jira/browse/LAU-800
After enabling integration tests, inadvertently disabled functional tests. This commit should fix that.
```
[ ] Yes
[x] No
```
=> LAU-800 re-enable functional tests

src/main/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtils.java
https://tools.hmcts.net/jira/browse/LAU-805
Subtract failed to delete users from total deleted users
```
[ ] Yes
[x] No
```
=> LAU-805 subtract failed to delete users from total deletions

src/main/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtils.java
Change date and time format to a more standard one, e.g 2023-10-20 16:23:22
```
[ ] Yes
[x] No
```
=> LAU-805 change date format

build.gradle
Bump logback
```
[ ] Yes
[x] No
```
=> LAU-823 bump logback version

src/main/java/uk/gov/hmcts/reform/idam/util/SecurityUtil.java
https://tools.hmcts.net/jira/browse/LAU-824
This change is to generate service auth token every 4 hours.
```
[ ] Yes
[x] No
```
=> LAU-824 generate service token every 4 hours

src/main/java/uk/gov/hmcts/reform/idam/service/UserRoleMergeService.java
Log case types that were merged into user
=> LAU-825 add case types to merged user log entry

charts/disposer-idam-user/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-831
Charts-job upgrade to 2.1.1
```
[ ] Yes
[x] No
```
=> lau-831 charts-job upgrade to 2.1.1

build.gradle
Remove explicit pitest version and leave for plugin to figure it out
=> fix pitest

src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/RoleAssignmentStubs.java, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/RoleAssignmentsSteps.java, src/integrationTest/resources/application-test.yaml, src/integrationTest/resources/features/role_assignments.feature, src/integrationTest/resources/wiremock/__files/roleAssignmentsResponsePage0.json, src/integrationTest/resources/wiremock/__files/roleAssignmentsResponsePage1.json, src/integrationTest/resources/wiremock/__files/roleAssignmentsResponsePage2.json, src/main/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolver.java, src/main/java/uk/gov/hmcts/reform/idam/service/UserRoleService.java, src/main/java/uk/gov/hmcts/reform/idam/service/remote/responses/RoleAssignmentResponse.java, src/test/java/uk/gov/hmcts/reform/idam/service/UserRoleServiceTest.java
[LAU-860](https://tools.hmcts.net/jira/browse/LAU-860)
Iterate over role assignment response pages if there are any
=> Lau 860 am filtering

README.md
Update readme with cnp-flux-config variables for extra functionality
=> Update readme with cnp-flux-config details

build.gradle, config/owasp/suppressions.xml
=> remove CVEs

charts/disposer-idam-user/Chart.yaml, src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/RetrySteps.java, src/integrationTest/resources/features/user_disposer.feature, src/main/java/uk/gov/hmcts/reform/idam/ApplicationExecutor.java, src/test/java/uk/gov/hmcts/reform/idam/ApplicationExecutorTest.java
https://tools.hmcts.net/jira/browse/LAU-913
Wrapping around try and catch
```
[ ] Yes
[x] No
```
=> LAU-913 adding try catch for any exception

src/main/java/uk/gov/hmcts/reform/idam/ApplicationExecutor.java, src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/test/java/uk/gov/hmcts/reform/idam/ApplicationExecutorTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-964
Always print out statistics, even if there was an exception
=> LAU-964 always print stats

src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[x] No
```
=> Remove unnecessary log.

build.gradle, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application-test.yaml, src/main/java/uk/gov/hmcts/reform/idam/Application.java, src/main/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolver.java, src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolverTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-1074
Added time limit to control how long a job can run. It will stop processing if overruns allowed time of the day.
```
[ ] Yes
[x] No
```
=> LAU-1074 add time limit to stop the job if overrun

src/main/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolver.java, src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolverTest.java, src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
Add logic to decide whether one day needs to be added or not to cut-off time
=> LAU-1099 better handle cut-off time

charts/disposer-idam-user/Chart.yaml
Bump job chart version
```
[ ] Yes
[x] No
```
=> Bump job helm chart version

src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java, src/main/java/uk/gov/hmcts/reform/idam/service/remote/responses/StaleUsersResponse.java, src/test/java/uk/gov/hmcts/reform/idam/service/StaleUsersServiceTest.java
Log how many pages are there
```
[ ] Yes
[x] No
```
=> log how many pages are there

src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java, src/main/java/uk/gov/hmcts/reform/idam/service/remote/responses/StaleUsersResponse.java, src/test/java/uk/gov/hmcts/reform/idam/service/StaleUsersServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-1275
Remove total pages log message
```
[ ] Yes
[x] No
```
=> LAU-1275 remove total pages log message
